/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge26;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void insertionSortTest1(){

        int[] arr1 = {8, 4, 23, 42, 16, 15};

        InsertionSort insertionSort = new InsertionSort();
        insertionSort.insertionSort(arr1);
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(arr1));
    }


    @Test
    public void insertionSortTest2(){

        int [] arr2 ={20, 18, 12, 8, 5, -2};

        InsertionSort insertionSort = new InsertionSort();
        insertionSort.insertionSort(arr2);
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(arr2));

    }
    @Test
    public void mergeSortTest1(){

        int[] arr1 = {8, 4, 23, 42, 16, 15};
        MergeSort mergeSort = new MergeSort();
        mergeSort.sort(arr1);
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(arr1));

    }

    @Test
    public void mergeSortTest2(){

        int [] arr2 ={20, 18, 12, 8, 5, -2};

        MergeSort mergeSort = new MergeSort();
        mergeSort.sort(arr2);
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(arr2));

    }
}
