/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge15;

public class App {
    public static void main(String[] args) {
            BinarySearchTree<Integer> binarySearchTree = new BinarySearchTree<>();
            binarySearchTree.insert(50);
            binarySearchTree.insert(10);
            binarySearchTree.insert(60);
            binarySearchTree.insert(5);
            binarySearchTree.insert(20);
            binarySearchTree.insert(55);
            binarySearchTree.insert(70);

            BinarySearchTree<String> jason = new BinarySearchTree<>();
            jason.insert("N");
            jason.insert("A");
            jason.insert("E");
            jason.insert("E");
            jason.insert("M");
            jason.insert("A");
            jason.insert("L");
            jason.insert("O");
            jason.insert("M");
            jason.insert("R");
            jason.insert("I");

//            System.out.println("Inorder traversal of Naim");
            jason.inorderTraversal();
        }
    }
