/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge15;

import org.w3c.dom.Node;

public class App {
    public static void main(String[] args) {


        BinarySearchTree<Integer> binarySearchContains = new BinarySearchTree<>();
        binarySearchContains.insert(23);
        binarySearchContains.insert(8);
        binarySearchContains.insert(42);
        binarySearchContains.insert(4);
        binarySearchContains.insert(16);
        binarySearchContains.insert(27);
        binarySearchContains.insert(85);

        System.out.println(binarySearchContains.contains(100));
//        System.out.println(binarySearchContains);

        binarySearchContains.inorderTraversal();
        System.out.println("");
        binarySearchContains.orderPost();
        System.out.println("");
        binarySearchContains.preOder200();
        System.out.println("");

        System.out.println(binarySearchContains.contains(23));

        BinarySearchTree<Integer> binarySearchTree2 = new BinarySearchTree<>();

        binarySearchTree2.insert(5); // Change this number to compare between the two trees .

        System.out.println(binarySearchTree2.compareTo(binarySearchContains));
        System.out.println(binarySearchContains.compareTo(binarySearchTree2));
        System.out.println(binarySearchTree2.compareTo(binarySearchContains));
    }
}
